/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LP;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis Carlos Rincon Gordo
 * @author Jeison Stiven Polanco Montaño
 */
public class Primera extends javax.swing.JFrame {

    //Variables
    
    int s=0;
    int r=0;
    int m=0;
    int d=0;
    
    
    /**
     * Creates new form Primera
     */
    public Primera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("MATEMAAP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Escoge las operaciones matematicas que deceas utilizar");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Sumar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setText("Restar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setText("Multiplicar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton5.setText("Dividir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Info");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton5))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(11, 11, 11)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton de informacion
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
        JOptionPane.showMessageDialog(null,"En esta aplicación podras escoger algunas aplicaciones matematicas para luego utilizarlas en otro apartado de nuestra app");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    //boton para restar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        r=1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    //boton para multiplicar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        m=1;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    //boton para dividir
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        d=1;

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    //boton para sumar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        s=1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    //boton para empezar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(r==1 && m==0 && d==0  && s==0){
        
             //Abrir nueva ventana
            Restar abrir1=new Restar();
            abrir1.setVisible(true);
            this.setVisible(false);
            //
             
             
        }
        if(r==0 && m==1 && d==0  && s==0){
        
            //Abrir nueva ventana
            Multiplicar abrir2=new Multiplicar();
            abrir2.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==0 && d==1  && s==0){
            
            //Abrir nueva ventana
            Dividir abrir3=new Dividir();
            abrir3.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==0 && d==0  && s==1){

            //Abrir nueva ventana
            Sumar abrir4=new Sumar();
            abrir4.setVisible(true);
            this.setVisible(false);
            //
            
        }
        if(r==0 && m==0 && d==0  && s==0){
        
            JOptionPane.showMessageDialog(null,"por favor dijita alguna operacion para continuar");
        }
        //conbinaciones de operaciones de dos
        
        if(r==1 && m==1 && d==0  && s==0){
        
            
            //Abrir nueva ventana
            RyM abrir5=new RyM();
            abrir5.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==1 && m==0 && d==1  && s==0){

            //Abrir nueva ventana
            RyD abrir6=new RyD();
            abrir6.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==1 && m==0 && d==0  && s==1){

            //Abrir nueva ventana
            RyS abrir7=new RyS();
            abrir7.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==1 && d==1  && s==0){
            
            //Abrir nueva ventana
            MyD abrir8=new MyD();
            abrir8.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==1 && d==0  && s==1){
        
            //Abrir nueva ventana
            MyS abrir9=new MyS();
            abrir9.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==0 && d==1  && s==1){
        
            //Abrir nueva ventana
            DyS abrir10=new DyS();
            abrir10.setVisible(true);
            this.setVisible(false);
            //
        }
        
        //conbinaciones de tres
        if(r==1 && m==1 && d==1  && s==0){
            
            //Abrir nueva ventana
            RyMyD abrir11=new RyMyD();
            abrir11.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==1 && m==0 && d==1  && s==1){
        
            //Abrir nueva ventana
            RyDyS abrir12=new RyDyS();
            abrir12.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==1 && m==1 && d==0  && s==1){
            
            //Abrir nueva ventana
            RyMyS abrir13=new RyMyS();
            abrir13.setVisible(true);
            this.setVisible(false);
            //
        }
        if(r==0 && m==1 && d==1  && s==1){
        
            //Abrir nueva ventana
            MyDyS abrir14=new MyDyS();
            abrir14.setVisible(true);
            this.setVisible(false);
            //
            
        }
        //combinaciones de 4
        
        if(r==1 && m==1 && d==1  && s==1){
        
            //Abrir nueva ventana
            RyMyDyS abrir15=new RyMyDyS();
            abrir15.setVisible(true);
            this.setVisible(false);
            //
            
        }
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Primera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
